"""
backend/comparison.py
Empirical Evaluation & Proof of Optimization:
Compares the average pick distance for sample customer orders under:
1. Unoptimized / Baseline shelf placement
2. Optimized shelf placement (frequency-based slotting)
Calculates distance savings and percentage efficiency improvement.
"""

from backend.layout_optimizer import LayoutOptimizer
from backend.route_optimizer import RouteOptimizer

def calculate_comparison_statistics(conn, warehouse, products, shelves, orders):
    """
    Simulates order picking across orders under:
    - Current/Baseline layout
    - Optimized layout generated by LayoutOptimizer
    
    Returns structured metrics proving optimization value.
    """
    optimizer = LayoutOptimizer()
    assignments, _ = optimizer.optimize(products, shelves)

    # Map product_id -> new_shelf_id
    optimized_shelf_map = {a["product_id"]: a["new_shelf_id"] for a in assignments}
    baseline_shelf_map = {p.id: p.assigned_shelf_id for p in products}

    route_opt = RouteOptimizer(warehouse)

    order_results = []
    total_before = 0.0
    total_after = 0.0

    # Evaluate across all available customer orders
    for order in orders:
        if not order.items:
            continue

        # Get shelf IDs under baseline placement
        baseline_shelves = [
            baseline_shelf_map.get(item["product_id"]) 
            for item in order.items 
            if baseline_shelf_map.get(item["product_id"]) is not None
        ]
        
        # Get shelf IDs under optimized placement
        optimized_shelves = [
            optimized_shelf_map.get(item["product_id"]) 
            for item in order.items 
            if optimized_shelf_map.get(item["product_id"]) is not None
        ]

        route_before = route_opt.solve_order_route(order.id, baseline_shelves)
        route_after = route_opt.solve_order_route(order.id, optimized_shelves)

        d_before = route_before["total_distance"]
        d_after = route_after["total_distance"]
        saved = max(0.0, round(d_before - d_after, 2))
        pct = round((saved / d_before * 100), 1) if d_before > 0 else 0.0

        total_before += d_before
        total_after += d_after

        order_results.append({
            "order_id": order.id,
            "customer_name": order.customer_name,
            "item_count": len(order.items),
            "distance_before": d_before,
            "distance_after": d_after,
            "distance_saved": saved,
            "pct_saved": pct,
            "algorithm": route_before["algorithm"]
        })

    num_orders = len(order_results)
    avg_before = round(total_before / num_orders, 2) if num_orders > 0 else 0.0
    avg_after = round(total_after / num_orders, 2) if num_orders > 0 else 0.0
    overall_saved = round(total_before - total_after, 2)
    overall_pct = round((overall_saved / total_before * 100), 1) if total_before > 0 else 0.0

    return {
        "orders_evaluated": num_orders,
        "avg_distance_before": avg_before,
        "avg_distance_after": avg_after,
        "total_distance_before": round(total_before, 2),
        "total_distance_after": round(total_after, 2),
        "total_distance_saved": overall_saved,
        "percent_reduction": overall_pct,
        "order_breakdown": order_results
    }
